query ($userId: Int, $type: MediaType, $status: MediaListStatus) {
  MediaListCollection(
    userId: $userId
    type: $type
    status: $status
    sort: UPDATED_TIME_DESC
  ) {
    lists {
      name
      isCustomList
      entries {
        id
        mediaId
        status
        score
        progress
        repeat
        notes
        updatedAt
        media {
          id
          title {
            romaji
            english
            userPreferred
          }
          coverImage {
            large
            medium
          }
          episodes
          status
          averageScore
          format
        }
      }
    }
  }
}
